### PR TITLE
TWS with IBC running in an rdesktop container.

### PR DESCRIPTION
**Pull request by gnzsnz**
first running version

 Changes to be committed:
	modified:   .gitignore
	modified:   .pre-commit-config.yaml
	new file:   Dockerfile.tws.template
	new file:   image-files/tws-scripts/start_session.sh
	new file:   latest/Dockerfile.tws
	new file:   latest/tws-scripts/start_session.sh
	new file:   tws-docker-compose.yml

to use it

```bash
docker compose -f tws-docker-compose.yml up
```

### CODE REVIEW

**Comment by gnzsnz** [comment]
[@nalon99](https://github.com/nalon99)

could you please check this branch?

you would need to

```bash
# pull code
git close https://github.com/gnzsnz/ib-gateway-docker
cd ib-gateway-docker
git switch tws-desktop
# run container
docker compose -f tws-docker-compose.yml up
```

Based on #43 I explored further the idea of using [docker-rdesktop](https://github.com/linuxserver/docker-rdesktop), and I have a very first working version.

the only thing that is working is the desktop environment it self, IBC and TWS. not much more at the moment. but is a good starting point.

If you could review this and provide feedback I would appreciate, after all it was your original idea to run TWS on the container. this will be a different container that ib-gateway-docker, but the codebase if common. I just needed a start-up script for [docker-rdesktop](https://github.com/linuxserver/docker-rdesktop) and a really simple `Dockerfile.tws`.

**Comment by gnzsnz** [comment]
Open points

- [ ] what we do with `CUSTOM_CONFIG`, it might not be needed for TWS
- [ ] implement SSH tunnel
- [ ] SSH for rdp
- [ ] how to manage ssh-agent, xfce is launching it already
- [ ] manage `abc` user password
- [ ] can we rename user `abc`
- [ ] timezone for TWS
- [ ] CI/CD pipeline
- [ ] pin rdesktop version, manage updates of rdesktop

**Comment by nalon99** [comment]
sorry for my late answer, too busy at work these days :-(
I followed your instructions to build this new image but when docker compose is starting the container it stops with the following error:
Error response from daemon: error gathering device information while adding custom device "/dev/dri": no such file or directory

**Comment by gnzsnz** [comment]
> Error response from daemon: error gathering device information while adding custom device "/dev/dri": no such file or directory

edit tws-docker-compose.yml and comment out these lines

```
    devices:
      - /dev/dri:/dev/dri #optional
```
it's a recommended setting, but it's optional.

**Comment by gnzsnz** [comment]
error message on log

```
algo-trader-tws-1  | 2023-11-25 18:34:44:465 IBC: detected frame entitled: Dow Jones Today's Top Ten; event=Focused
algo-trader-tws-1  | java.util.concurrent.CompletionException: com.teamdev.jxbrowser.engine.MissingDependencyException: Missing dependencies have been detected:
algo-trader-tws-1  |    chromium => libnssutil3.so libnss3.so libsmime3.so libnspr4.so
algo-trader-tws-1  |    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
algo-trader-tws-1  |    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
algo-trader-tws-1  |    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
algo-trader-tws-1  |    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
algo-trader-tws-1  |    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
algo-trader-tws-1  |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
algo-trader-tws-1  |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
algo-trader-tws-1  |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
algo-trader-tws-1  |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
algo-trader-tws-1  |    at java.lang.Thread.run(Thread.java:748)
algo-trader-tws-1  | Caused by: com.teamdev.jxbrowser.engine.MissingDependencyException: Missing dependencies have been detected:
algo-trader-tws-1  |    chromium => libnssutil3.so libnss3.so libsmime3.so libnspr4.so
algo-trader-tws-1  |    at com.teamdev.jxbrowser.engine.internal.LinuxDependencies.lambda$checkAvailability$1(LinuxDependencies.java:82)
algo-trader-tws-1  |    at java.util.Optional.ifPresent(Optional.java:159)
algo-trader-tws-1  |    at com.teamdev.jxbrowser.engine.internal.LinuxDependencies.checkAvailability(LinuxDependencies.java:67)
algo-trader-tws-1  |    at com.teamdev.jxbrowser.engine.internal.EngineImpl.newInstance(EngineImpl.java:152)
algo-trader-tws-1  |    at com.teamdev.jxbrowser.engine.Engine.newInstance(Engine.java:163)
algo-trader-tws-1  |    at feature.webapp.F.b(F.java:800)
algo-trader-tws-1  |    at feature.webapp.F.a(F.java:709)
algo-trader-tws-1  |    at feature.webapp.F.c(F.java:664)
algo-trader-tws-1  |    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
al
```

missing ubuntu packages `libnspr4 libnss3`

**Comment by gnzsnz** [comment]
TWS running in a docker-rdesktop container with XFCE and IBC

Screenshot 2023-11-25 at 20 46 53

**Comment by ownrepo1s** [comment]
> > Error response from daemon: error gathering device information while adding custom device "/dev/dri": no such file or directory
> 
> edit tws-docker-compose.yml and comment out these lines
> 
> ```
>     devices:
>       - /dev/dri:/dev/dri #optional
> ```
> 
> it's a recommended setting, but it's optional.

This fixed the same issue I see when I run `docker compose up` on [https://github.com/gnzsnz/ib-gateway-docker/blob/master/tws-docker-compose.yml](https://github.com/gnzsnz/ib-gateway-docker/blob/master/tws-docker-compose.yml) on the main channel.

**Comment by gnzsnz** [comment]
If you get an error due to /dev/dri, you have 2 options, comment out that
line in compose file. Or enable it on your host.

**Pull request merged**
